disabled_rules:
  - multiple_closures_with_trailing_closure
  - implicit_optional_initialization

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_function_declarations: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 1
    error: 0
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true
  excluded: ["id", "ts", "to", "m", "q", "e", "r", "f", "d", "v", "ti"]

cyclomatic_complexity:
  warning: 20
  error: 30

reporter: "xcode"

