// swift-tools-version:6.0
// Builds the UI-free session core that the macOS app shares with the Linux `as-core` CLI.
// Sources are referenced in place from AgentSessions/; the Xcode project still compiles
// them itself, so this manifest must only list files that build without AppKit/SwiftUI.
import PackageDescription

let coreSources = [
    "AgentSessions/AntigravityResume/AntigravityResumeTypes.swift",
    "AgentSessions/ClaudeResume/ClaudeResumeCommandBuilder.swift",
    "AgentSessions/ClaudeResume/ClaudeSessionIDHelper.swift",
    "AgentSessions/Cline/ClineSourceDescriptor.swift",
    "AgentSessions/Copilot/CopilotSourceDescriptor.swift",
    "AgentSessions/CopilotResume/CopilotResumeCommandBuilder.swift",
    "AgentSessions/Cursor/CursorBackendDetector.swift",
    "AgentSessions/Cursor/CursorSourceDescriptor.swift",
    "AgentSessions/Devin/DevinSourceDescriptor.swift",
    "AgentSessions/Devin/DevinSqliteReader.swift",
    "AgentSessions/Droid/DroidSourceDescriptor.swift",
    "AgentSessions/Fx/FxSourceDescriptor.swift",
    "AgentSessions/Grok/GrokSourceDescriptor.swift",
    "AgentSessions/Hermes/HermesSourceDescriptor.swift",
    "AgentSessions/Indexing/DB.swift",
    "AgentSessions/Indexing/SessionMetaRepository.swift",
    "AgentSessions/Kimi/KimiSourceDescriptor.swift",
    "AgentSessions/Model/AntigravitySourceDescriptor.swift",
    "AgentSessions/Model/ClaudeSourceDescriptor.swift",
    "AgentSessions/Model/CodexSourceDescriptor.swift",
    "AgentSessions/Model/OpenClawSourceDescriptor.swift",
    "AgentSessions/Model/Session.swift",
    "AgentSessions/Model/SessionEvent.swift",
    "AgentSessions/Model/SessionSource.swift",
    "AgentSessions/Model/SessionSourceDescriptor.swift",
    "AgentSessions/Model/SessionSourceDescriptorCatalog.swift",
    "AgentSessions/OpenCode/OpenCodeBackendDetector.swift",
    "AgentSessions/OpenCode/OpenCodeSourceDescriptor.swift",
    "AgentSessions/OpenCode/OpenCodeSqliteReader.swift",
    "AgentSessions/OpenCodeResume/OpenCodeResumeCommandBuilder.swift",
    "AgentSessions/Pi/PiSourceDescriptor.swift",
    "AgentSessions/Qwen/QwenSourceDescriptor.swift",
    "AgentSessions/Resume/CodexResumeCommandBuilder.swift",
    "AgentSessions/Resume/ShellQuoting.swift",
    "AgentSessions/Search/SearchIngestService.swift",
    "AgentSessions/Search/SessionSearchTextBuilder.swift",
    "AgentSessions/Services/AntigravitySessionDiscovery.swift",
    "AgentSessions/Services/AntigravitySessionParser.swift",
    "AgentSessions/Services/AntigravityTranscriptParser.swift",
    "AgentSessions/Services/ClaudeArchiveRestore.swift",
    "AgentSessions/Services/ClaudeSessionParser.swift",
    "AgentSessions/Services/ClineSessionDiscovery.swift",
    "AgentSessions/Services/ClineSessionParser.swift",
    "AgentSessions/Services/CodexSessionParser.swift",
    "AgentSessions/Services/CodexSideChatLogReader.swift",
    "AgentSessions/Services/CopilotSessionParser.swift",
    "AgentSessions/Services/CursorSessionDiscovery.swift",
    "AgentSessions/Services/CursorSessionParser.swift",
    "AgentSessions/Services/DevinSessionDiscovery.swift",
    "AgentSessions/Services/DevinSessionParser.swift",
    "AgentSessions/Services/DroidSessionDiscovery.swift",
    "AgentSessions/Services/DroidSessionParser.swift",
    "AgentSessions/Services/FxSessionDiscovery.swift",
    "AgentSessions/Services/FxSessionParser.swift",
    "AgentSessions/Services/GrokSessionDiscovery.swift",
    "AgentSessions/Services/GrokSessionParser.swift",
    "AgentSessions/Services/HermesSessionDiscovery.swift",
    "AgentSessions/Services/HermesSessionParser.swift",
    "AgentSessions/Services/KimiSessionDiscovery.swift",
    "AgentSessions/Services/KimiSessionParser.swift",
    "AgentSessions/Services/OpenClawSessionDiscovery.swift",
    "AgentSessions/Services/OpenClawSessionParser.swift",
    "AgentSessions/Services/OpenCodeSessionDiscovery.swift",
    "AgentSessions/Services/OpenCodeSessionParser.swift",
    "AgentSessions/Services/PiSessionDiscovery.swift",
    "AgentSessions/Services/PiSessionParser.swift",
    "AgentSessions/Services/QwenSessionDiscovery.swift",
    "AgentSessions/Services/QwenSessionParser.swift",
    "AgentSessions/Services/SessionDiscovery.swift",
    "AgentSessions/Services/SessionIndexingEngine.swift",
    "AgentSessions/Services/SessionTranscriptBuilder.swift",
    "AgentSessions/Services/ToolTextBlockNormalizer.swift",
    "AgentSessions/Services/TranscriptRenderMode.swift",
    "AgentSessions/Support/AppRuntime.swift",
    "AgentSessions/Support/FeatureFlags.swift",
    "AgentSessions/Support/FileProbing.swift",
    "AgentSessions/Support/PerfSignpost.swift",
    "AgentSessions/Support/PlatformCompat.swift",
    "AgentSessions/Utilities/AppDateFormatting.swift",
    "AgentSessions/Utilities/JSONLReader.swift",
    "AgentSessions/Utilities/LRUCache.swift",
    "AgentSessions/Utilities/PrettyJSON.swift",
    "AgentSessions/Utilities/ProgressThrottler.swift",
    "AgentSessions/Utilities/ReverseJSONLTailReader.swift",
    "AgentSessions/Views/Preferences/PreferencesConstants.swift",
]

let package = Package(
    name: "AgentSessionsCore",
    platforms: [.macOS(.v14)],
    dependencies: [
        // CryptoKit's API on Linux; the macOS build keeps using CryptoKit.
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.0.0"),
    ],
    targets: [
        // macOS ships a SQLite3 module in the SDK; Linux needs libsqlite3-dev plus a module map.
        .systemLibrary(
            name: "SQLite3",
            path: "linux/Sources/SQLite3",
            providers: [.apt(["libsqlite3-dev"])]
        ),
        .executableTarget(
            name: "as-core",
            dependencies: [
                .product(name: "Crypto", package: "swift-crypto", condition: .when(platforms: [.linux])),
                .target(name: "SQLite3", condition: .when(platforms: [.linux])),
            ],
            path: ".",
            sources: coreSources + ["cli/as-core/main.swift", "cli/as-core/Drivers.swift", "cli/as-core/Output.swift", "cli/as-core/Commands.swift", "cli/as-core/Resume.swift"],
            swiftSettings: [.swiftLanguageMode(.v5)],
            // Link SQLite statically on Linux (libsqlite3-dev ships libsqlite3.a), so the
            // released binary runs on distros without libsqlite3.so.0 installed.
            linkerSettings: [.unsafeFlags(["-l:libsqlite3.a"], .when(platforms: [.linux]))]
        ),
    ]
)
