name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Xcode version
        run: xcodebuild -version
      - name: Build & Test
        run: |
          xcodebuild -project AgentSessions.xcodeproj -scheme AgentSessions -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO test | xcpretty || exit ${PIPESTATUS[0]}
        shell: bash
      - name: Upload logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs
          path: ~/Library/Logs/DiagnosticReports
