name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Xcode version
        run: xcodebuild -version
      - name: Build (macOS, no signing)
        shell: bash
        run: |
          set -o pipefail
          xcodebuild \
            -project AgentSessions.xcodeproj \
            -scheme AgentSessions \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            build
